name: ExamplePlugin
version: ${project.version}
main: mc.cushypro.PluginName.MyMain
authors: [ CushyPro ]
description: Example Plugin
commands:
  exam:
    aliases: []
    usage: /hm help
    description: A
    permission: hm.use